[package]
name = "sc_memory"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "sc_memory"
path = "src/main.rs"

[dependencies]
windows = { version = "0.56", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_SystemInformation"
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = "z"
lto = true
strip = true
