import type { Locale } from "@/stores/userPreferencesStore";

/**
 * Advisor screens are authenticated-only, so their catalog is intentionally
 * kept outside the public-site dictionaries.  Keys are the English source
 * strings used by `t()` and by the i18n DOM compatibility bridge.
 */
const EN = {
  "AI Advisor": "AI Advisor", "BIOS Advisor": "BIOS Advisor",
  "System Profile": "System Profile", "Advisor Coverage": "Advisor Coverage",
  "Live Telemetry": "Live Telemetry", "System Hardware": "System Hardware",
  "Initializing data sources…": "Initializing data sources…",
  "Loading advanced hardware info…": "Loading advanced hardware info…",
  "Diagnosis complete": "Diagnosis complete", "Recommendation": "Recommendation",
  "Recommendations": "Recommendations", "No analysis yet": "No analysis yet",
  "Run Analysis": "Run Analysis", "Re-analyze": "Re-analyze",
  "Analysis complete": "Analysis complete", "Firmware Analytics": "Firmware Analytics",
  "Hardware Profile": "Hardware Profile", "Detected Hardware": "Detected Hardware",
  "Boot & Security": "Boot & Security", "Loading advanced system data…": "Loading advanced system data…",
  "Dismiss": "Dismiss", "Score unchanged": "Score unchanged",
  "How to Access Your BIOS": "How to Access Your BIOS",
  "Show BIOS Steps": "Show BIOS Steps", "Hide Steps": "Hide Steps",
  "Detection Detail": "Detection Detail", "Confidence:": "Confidence:",
  "What it is": "What it is", "Pros": "Pros", "Cons": "Cons",
  "When NOT to change": "When NOT to change", "Where to find in BIOS": "Where to find in BIOS",
  "Collecting hardware telemetry...": "Collecting hardware telemetry...",
  "Running firmware behavior analysis...": "Running firmware behavior analysis...",
  "Generating AI explanation...": "Generating AI explanation...",
} as const;

type Key = keyof typeof EN;
type Catalog = Record<Key, string>;
const catalog = (values: Partial<Catalog>): Catalog => ({ ...EN, ...values });

export const ADVISOR_AUTH_TRANSLATIONS: Partial<Record<Locale, Catalog>> = {
  en: catalog({}),
  "zh-CN": catalog({"System Profile":"系统配置","Advisor Coverage":"顾问覆盖范围","Live Telemetry":"实时遥测","System Hardware":"系统硬件","Initializing data sources…":"正在初始化数据源…","Loading advanced hardware info…":"正在加载高级硬件信息…","Diagnosis complete":"诊断完成","Recommendation":"建议","Recommendations":"建议","No analysis yet":"尚无分析","Run Analysis":"运行分析","Re-analyze":"重新分析","Analysis complete":"分析完成","Firmware Analytics":"固件分析","Hardware Profile":"硬件配置","Detected Hardware":"检测到的硬件","Boot & Security":"启动与安全","Loading advanced system data…":"正在加载高级系统数据…","Dismiss":"关闭","Score unchanged":"评分未变化","How to Access Your BIOS":"如何进入 BIOS","Show BIOS Steps":"显示 BIOS 步骤","Hide Steps":"隐藏步骤","Detection Detail":"检测详情","Confidence:":"置信度：","What it is":"说明","Pros":"优点","Cons":"缺点","When NOT to change":"不应更改的情况","Where to find in BIOS":"在 BIOS 中的位置","Collecting hardware telemetry...":"正在收集硬件遥测数据...","Running firmware behavior analysis...":"正在运行固件行为分析...","Generating AI explanation...":"正在生成 AI 说明..."}),
  es: catalog({"System Profile":"Perfil del sistema","Advisor Coverage":"Cobertura del asesor","Live Telemetry":"Telemetría en vivo","System Hardware":"Hardware del sistema","Initializing data sources…":"Inicializando fuentes de datos…","Loading advanced hardware info…":"Cargando información avanzada de hardware…","Diagnosis complete":"Diagnóstico completado","Recommendation":"Recomendación","Recommendations":"Recomendaciones","No analysis yet":"Aún no hay análisis","Run Analysis":"Ejecutar análisis","Re-analyze":"Volver a analizar","Analysis complete":"Análisis completado","Firmware Analytics":"Análisis de firmware","Hardware Profile":"Perfil de hardware","Detected Hardware":"Hardware detectado","Boot & Security":"Arranque y seguridad","Loading advanced system data…":"Cargando datos avanzados del sistema…","Dismiss":"Descartar","Score unchanged":"Puntuación sin cambios","How to Access Your BIOS":"Cómo acceder a tu BIOS","Show BIOS Steps":"Mostrar pasos de BIOS","Hide Steps":"Ocultar pasos","Detection Detail":"Detalle de detección","Confidence:":"Confianza:","What it is":"Qué es","Pros":"Ventajas","Cons":"Desventajas","When NOT to change":"Cuándo NO cambiar","Where to find in BIOS":"Dónde encontrarlo en BIOS","Collecting hardware telemetry...":"Recopilando telemetría de hardware...","Running firmware behavior analysis...":"Ejecutando análisis de comportamiento del firmware...","Generating AI explanation...":"Generando explicación de AI..."}),
  fr: catalog({"System Profile":"Profil système","Advisor Coverage":"Couverture du conseiller","Live Telemetry":"Télémétrie en direct","System Hardware":"Matériel système","Initializing data sources…":"Initialisation des sources de données…","Loading advanced hardware info…":"Chargement des informations matérielles avancées…","Diagnosis complete":"Diagnostic terminé","Recommendation":"Recommandation","Recommendations":"Recommandations","No analysis yet":"Aucune analyse pour l’instant","Run Analysis":"Lancer l’analyse","Re-analyze":"Analyser à nouveau","Analysis complete":"Analyse terminée","Firmware Analytics":"Analyse du firmware","Hardware Profile":"Profil matériel","Detected Hardware":"Matériel détecté","Boot & Security":"Démarrage et sécurité","Loading advanced system data…":"Chargement des données système avancées…","Dismiss":"Fermer","Score unchanged":"Score inchangé","How to Access Your BIOS":"Comment accéder à votre BIOS","Show BIOS Steps":"Afficher les étapes BIOS","Hide Steps":"Masquer les étapes","Detection Detail":"Détail de détection","Confidence:":"Confiance :","What it is":"Qu’est-ce que c’est","Pros":"Avantages","Cons":"Inconvénients","When NOT to change":"Quand NE PAS modifier","Where to find in BIOS":"Où le trouver dans le BIOS","Collecting hardware telemetry...":"Collecte de la télémétrie matérielle...","Running firmware behavior analysis...":"Analyse du comportement du firmware...","Generating AI explanation...":"Génération de l’explication AI..."}),
  de: catalog({"System Profile":"Systemprofil","Advisor Coverage":"Beraterabdeckung","Live Telemetry":"Live-Telemetrie","System Hardware":"Systemhardware","Initializing data sources…":"Datenquellen werden initialisiert…","Loading advanced hardware info…":"Erweiterte Hardwareinformationen werden geladen…","Diagnosis complete":"Diagnose abgeschlossen","Recommendation":"Empfehlung","Recommendations":"Empfehlungen","No analysis yet":"Noch keine Analyse","Run Analysis":"Analyse starten","Re-analyze":"Erneut analysieren","Analysis complete":"Analyse abgeschlossen","Firmware Analytics":"Firmware-Analyse","Hardware Profile":"Hardwareprofil","Detected Hardware":"Erkannte Hardware","Boot & Security":"Start und Sicherheit","Loading advanced system data…":"Erweiterte Systemdaten werden geladen…","Dismiss":"Schließen","Score unchanged":"Punktzahl unverändert","How to Access Your BIOS":"So öffnen Sie Ihr BIOS","Show BIOS Steps":"BIOS-Schritte anzeigen","Hide Steps":"Schritte ausblenden","Detection Detail":"Erkennungsdetails","Confidence:":"Konfidenz:","What it is":"Was es ist","Pros":"Vorteile","Cons":"Nachteile","When NOT to change":"Wann NICHT ändern","Where to find in BIOS":"Wo im BIOS zu finden","Collecting hardware telemetry...":"Hardware-Telemetrie wird erfasst...","Running firmware behavior analysis...":"Firmware-Verhaltensanalyse läuft...","Generating AI explanation...":"AI-Erklärung wird erstellt..."}),
  "pt-BR": catalog({"System Profile":"Perfil do sistema","Advisor Coverage":"Cobertura do consultor","Live Telemetry":"Telemetria ao vivo","System Hardware":"Hardware do sistema","Initializing data sources…":"Inicializando fontes de dados…","Loading advanced hardware info…":"Carregando informações avançadas de hardware…","Diagnosis complete":"Diagnóstico concluído","Recommendation":"Recomendação","Recommendations":"Recomendações","No analysis yet":"Ainda não há análise","Run Analysis":"Executar análise","Re-analyze":"Analisar novamente","Analysis complete":"Análise concluída","Firmware Analytics":"Análise de firmware","Hardware Profile":"Perfil de hardware","Detected Hardware":"Hardware detectado","Boot & Security":"Inicialização e segurança","Loading advanced system data…":"Carregando dados avançados do sistema…","Dismiss":"Dispensar","Score unchanged":"Pontuação inalterada","How to Access Your BIOS":"Como acessar sua BIOS","Show BIOS Steps":"Mostrar etapas da BIOS","Hide Steps":"Ocultar etapas","Detection Detail":"Detalhe da detecção","Confidence:":"Confiança:","What it is":"O que é","Pros":"Prós","Cons":"Contras","When NOT to change":"Quando NÃO alterar","Where to find in BIOS":"Onde encontrar na BIOS","Collecting hardware telemetry...":"Coletando telemetria de hardware...","Running firmware behavior analysis...":"Executando análise de comportamento do firmware...","Generating AI explanation...":"Gerando explicação de AI..."}),
  ru: catalog({"System Profile":"Профиль системы","Advisor Coverage":"Охват советника","Live Telemetry":"Телеметрия в реальном времени","System Hardware":"Оборудование системы","Initializing data sources…":"Инициализация источников данных…","Loading advanced hardware info…":"Загрузка расширенной информации об оборудовании…","Diagnosis complete":"Диагностика завершена","Recommendation":"Рекомендация","Recommendations":"Рекомендации","No analysis yet":"Анализа пока нет","Run Analysis":"Запустить анализ","Re-analyze":"Анализировать снова","Analysis complete":"Анализ завершен","Firmware Analytics":"Аналитика прошивки","Hardware Profile":"Профиль оборудования","Detected Hardware":"Обнаруженное оборудование","Boot & Security":"Загрузка и безопасность","Loading advanced system data…":"Загрузка расширенных системных данных…","Dismiss":"Закрыть","Score unchanged":"Оценка не изменилась","How to Access Your BIOS":"Как войти в BIOS","Show BIOS Steps":"Показать шаги BIOS","Hide Steps":"Скрыть шаги","Detection Detail":"Сведения об обнаружении","Confidence:":"Достоверность:","What it is":"Что это","Pros":"Плюсы","Cons":"Минусы","When NOT to change":"Когда НЕ следует менять","Where to find in BIOS":"Где найти в BIOS","Collecting hardware telemetry...":"Сбор телеметрии оборудования...","Running firmware behavior analysis...":"Выполняется анализ поведения прошивки...","Generating AI explanation...":"Создается объяснение AI..."}),
};

Object.assign(ADVISOR_AUTH_TRANSLATIONS, {
  hi: catalog({"System Profile":"सिस्टम प्रोफ़ाइल","Advisor Coverage":"सलाहकार कवरेज","Live Telemetry":"लाइव टेलीमेट्री","System Hardware":"सिस्टम हार्डवेयर","Initializing data sources…":"डेटा स्रोत शुरू किए जा रहे हैं…","Loading advanced hardware info…":"उन्नत हार्डवेयर जानकारी लोड हो रही है…","Diagnosis complete":"निदान पूरा हुआ","Recommendation":"सिफारिश","Recommendations":"सिफारिशें","No analysis yet":"अभी कोई विश्लेषण नहीं","Run Analysis":"विश्लेषण चलाएँ","Re-analyze":"फिर से विश्लेषण करें","Analysis complete":"विश्लेषण पूरा हुआ","Firmware Analytics":"फर्मवेयर विश्लेषण","Hardware Profile":"हार्डवेयर प्रोफ़ाइल","Detected Hardware":"पहचाना गया हार्डवेयर","Boot & Security":"बूट और सुरक्षा","Loading advanced system data…":"उन्नत सिस्टम डेटा लोड हो रहा है…","Dismiss":"खारिज करें","Score unchanged":"स्कोर अपरिवर्तित","How to Access Your BIOS":"अपने BIOS तक कैसे पहुँचें","Show BIOS Steps":"BIOS चरण दिखाएँ","Hide Steps":"चरण छिपाएँ","Detection Detail":"पहचान विवरण","Confidence:":"विश्वास:","What it is":"यह क्या है","Pros":"लाभ","Cons":"हानियाँ","When NOT to change":"कब न बदलें","Where to find in BIOS":"BIOS में कहाँ पाएँ","Collecting hardware telemetry...":"हार्डवेयर टेलीमेट्री एकत्रित हो रही है...","Running firmware behavior analysis...":"फर्मवेयर व्यवहार विश्लेषण चल रहा है...","Generating AI explanation...":"AI स्पष्टीकरण बनाया जा रहा है..."}),
  ar: catalog({"System Profile":"ملف النظام","Advisor Coverage":"تغطية المستشار","Live Telemetry":"القياس عن بُعد المباشر","System Hardware":"أجهزة النظام","Initializing data sources…":"جارٍ تهيئة مصادر البيانات…","Loading advanced hardware info…":"جارٍ تحميل معلومات الأجهزة المتقدمة…","Diagnosis complete":"اكتمل التشخيص","Recommendation":"توصية","Recommendations":"توصيات","No analysis yet":"لا يوجد تحليل بعد","Run Analysis":"تشغيل التحليل","Re-analyze":"إعادة التحليل","Analysis complete":"اكتمل التحليل","Firmware Analytics":"تحليلات البرنامج الثابت","Hardware Profile":"ملف الأجهزة","Detected Hardware":"الأجهزة المكتشفة","Boot & Security":"الإقلاع والأمان","Loading advanced system data…":"جارٍ تحميل بيانات النظام المتقدمة…","Dismiss":"تجاهل","Score unchanged":"النتيجة دون تغيير","How to Access Your BIOS":"كيفية الوصول إلى BIOS","Show BIOS Steps":"إظهار خطوات BIOS","Hide Steps":"إخفاء الخطوات","Detection Detail":"تفاصيل الاكتشاف","Confidence:":"الثقة:","What it is":"ما هو","Pros":"الإيجابيات","Cons":"السلبيات","When NOT to change":"متى لا تغيّر","Where to find in BIOS":"مكان العثور عليه في BIOS","Collecting hardware telemetry...":"جارٍ جمع قياس الأجهزة عن بُعد...","Running firmware behavior analysis...":"جارٍ تحليل سلوك البرنامج الثابت...","Generating AI explanation...":"جارٍ إنشاء شرح AI..."}),
  ja: catalog({"System Profile":"システムプロファイル","Advisor Coverage":"アドバイザーの対象範囲","Live Telemetry":"ライブテレメトリ","System Hardware":"システムハードウェア","Initializing data sources…":"データソースを初期化中…","Loading advanced hardware info…":"詳細なハードウェア情報を読み込み中…","Diagnosis complete":"診断完了","Recommendation":"推奨","Recommendations":"推奨事項","No analysis yet":"分析はまだありません","Run Analysis":"分析を実行","Re-analyze":"再分析","Analysis complete":"分析完了","Firmware Analytics":"ファームウェア分析","Hardware Profile":"ハードウェアプロファイル","Detected Hardware":"検出されたハードウェア","Boot & Security":"起動とセキュリティ","Loading advanced system data…":"詳細なシステムデータを読み込み中…","Dismiss":"閉じる","Score unchanged":"スコアは変化なし","How to Access Your BIOS":"BIOS へのアクセス方法","Show BIOS Steps":"BIOS 手順を表示","Hide Steps":"手順を隠す","Detection Detail":"検出の詳細","Confidence:":"信頼度:","What it is":"概要","Pros":"長所","Cons":"短所","When NOT to change":"変更しない場合","Where to find in BIOS":"BIOS 内の場所","Collecting hardware telemetry...":"ハードウェアテレメトリを収集中...","Running firmware behavior analysis...":"ファームウェア動作を分析中...","Generating AI explanation...":"AI の説明を生成中..."}),
  ko: catalog({"System Profile":"시스템 프로필","Advisor Coverage":"Advisor 적용 범위","Live Telemetry":"실시간 텔레메트리","System Hardware":"시스템 하드웨어","Initializing data sources…":"데이터 소스를 초기화하는 중…","Loading advanced hardware info…":"고급 하드웨어 정보를 불러오는 중…","Diagnosis complete":"진단 완료","Recommendation":"권장 사항","Recommendations":"권장 사항","No analysis yet":"아직 분석이 없습니다","Run Analysis":"분석 실행","Re-analyze":"다시 분석","Analysis complete":"분석 완료","Firmware Analytics":"펌웨어 분석","Hardware Profile":"하드웨어 프로필","Detected Hardware":"감지된 하드웨어","Boot & Security":"부팅 및 보안","Loading advanced system data…":"고급 시스템 데이터를 불러오는 중…","Dismiss":"닫기","Score unchanged":"점수 변경 없음","How to Access Your BIOS":"BIOS에 액세스하는 방법","Show BIOS Steps":"BIOS 단계 표시","Hide Steps":"단계 숨기기","Detection Detail":"감지 세부 정보","Confidence:":"신뢰도:","What it is":"설명","Pros":"장점","Cons":"단점","When NOT to change":"변경하지 말아야 할 때","Where to find in BIOS":"BIOS에서 찾는 위치","Collecting hardware telemetry...":"하드웨어 텔레메트리를 수집하는 중...","Running firmware behavior analysis...":"펌웨어 동작을 분석하는 중...","Generating AI explanation...":"AI 설명을 생성하는 중..."}),
  tr: catalog({"System Profile":"Sistem Profili","Advisor Coverage":"Danışman kapsamı","Live Telemetry":"Canlı telemetri","System Hardware":"Sistem donanımı","Initializing data sources…":"Veri kaynakları başlatılıyor…","Loading advanced hardware info…":"Gelişmiş donanım bilgisi yükleniyor…","Diagnosis complete":"Tanılama tamamlandı","Recommendation":"Öneri","Recommendations":"Öneriler","No analysis yet":"Henüz analiz yok","Run Analysis":"Analizi çalıştır","Re-analyze":"Yeniden analiz et","Analysis complete":"Analiz tamamlandı","Firmware Analytics":"Üretici yazılımı analizi","Hardware Profile":"Donanım profili","Detected Hardware":"Algılanan donanım","Boot & Security":"Önyükleme ve güvenlik","Loading advanced system data…":"Gelişmiş sistem verileri yükleniyor…","Dismiss":"Kapat","Score unchanged":"Puan değişmedi","How to Access Your BIOS":"BIOS'a nasıl erişilir","Show BIOS Steps":"BIOS adımlarını göster","Hide Steps":"Adımları gizle","Detection Detail":"Algılama ayrıntısı","Confidence:":"Güven:","What it is":"Nedir","Pros":"Artılar","Cons":"Eksiler","When NOT to change":"Ne zaman değiştirilmemeli","Where to find in BIOS":"BIOS'ta nerede bulunur","Collecting hardware telemetry...":"Donanım telemetrisi toplanıyor...","Running firmware behavior analysis...":"Üretici yazılımı davranışı analiz ediliyor...","Generating AI explanation...":"AI açıklaması oluşturuluyor..."}),
  bn: catalog({"System Profile":"সিস্টেম প্রোফাইল","Advisor Coverage":"উপদেষ্টার কভারেজ","Live Telemetry":"লাইভ টেলিমেট্রি","System Hardware":"সিস্টেম হার্ডওয়্যার","Diagnosis complete":"ডায়াগনসিস সম্পন্ন","Recommendation":"সুপারিশ","Recommendations":"সুপারিশসমূহ","No analysis yet":"এখনও কোনো বিশ্লেষণ নেই","Run Analysis":"বিশ্লেষণ চালান","Re-analyze":"পুনরায় বিশ্লেষণ করুন","Analysis complete":"বিশ্লেষণ সম্পন্ন","Dismiss":"বন্ধ করুন","Pros":"সুবিধা","Cons":"অসুবিধা","What it is":"এটি কী","Confidence:":"আত্মবিশ্বাস:","Hide Steps":"ধাপ লুকান","Show BIOS Steps":"BIOS ধাপ দেখান"}),
  pa: catalog({"System Profile":"ਸਿਸਟਮ ਪ੍ਰੋਫਾਈਲ","Advisor Coverage":"ਸਲਾਹਕਾਰ ਕਵਰੇਜ","Live Telemetry":"ਲਾਈਵ ਟੈਲੀਮੈਟਰੀ","System Hardware":"ਸਿਸਟਮ ਹਾਰਡਵੇਅਰ","Diagnosis complete":"ਨਿਦਾਨ ਪੂਰਾ ਹੋਇਆ","Recommendation":"ਸਿਫਾਰਸ਼","Recommendations":"ਸਿਫਾਰਸ਼ਾਂ","No analysis yet":"ਹਾਲੇ ਕੋਈ ਵਿਸ਼ਲੇਸ਼ਣ ਨਹੀਂ","Run Analysis":"ਵਿਸ਼ਲੇਸ਼ਣ ਚਲਾਓ","Re-analyze":"ਦੁਬਾਰਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ","Analysis complete":"ਵਿਸ਼ਲੇਸ਼ਣ ਪੂਰਾ ਹੋਇਆ","Dismiss":"ਖਾਰਜ ਕਰੋ","Pros":"ਫਾਇਦੇ","Cons":"ਨੁਕਸਾਨ","What it is":"ਇਹ ਕੀ ਹੈ","Confidence:":"ਭਰੋਸਾ:","Hide Steps":"ਕਦਮ ਲੁਕਾਓ","Show BIOS Steps":"BIOS ਕਦਮ ਦਿਖਾਓ"}),
  id: catalog({"System Profile":"Profil Sistem","Advisor Coverage":"Cakupan Advisor","Live Telemetry":"Telemetri langsung","System Hardware":"Perangkat keras sistem","Diagnosis complete":"Diagnosis selesai","Recommendation":"Rekomendasi","Recommendations":"Rekomendasi","No analysis yet":"Belum ada analisis","Run Analysis":"Jalankan analisis","Re-analyze":"Analisis ulang","Analysis complete":"Analisis selesai","Dismiss":"Tutup","Pros":"Kelebihan","Cons":"Kekurangan","What it is":"Apa ini","Confidence:":"Keyakinan:","Hide Steps":"Sembunyikan langkah","Show BIOS Steps":"Tampilkan langkah BIOS"}),
  te: catalog({"System Profile":"సిస్టమ్ ప్రొఫైల్","Advisor Coverage":"సలహాదారు పరిధి","Live Telemetry":"ప్రత్యక్ష టెలిమెట్రీ","System Hardware":"సిస్టమ్ హార్డ్‌వేర్","Diagnosis complete":"నిర్ధారణ పూర్తయింది","Recommendation":"సిఫార్సు","Recommendations":"సిఫార్సులు","No analysis yet":"ఇంకా విశ్లేషణ లేదు","Run Analysis":"విశ్లేషణ నడపండి","Re-analyze":"మళ్లీ విశ్లేషించండి","Analysis complete":"విశ్లేషణ పూర్తయింది","Dismiss":"మూసివేయి","Pros":"ప్రయోజనాలు","Cons":"లోపాలు","What it is":"ఇది ఏమిటి","Confidence:":"విశ్వాసం:","Hide Steps":"దశలను దాచు","Show BIOS Steps":"BIOS దశలను చూపు"}),
  mr: catalog({"System Profile":"सिस्टम प्रोफाइल","Advisor Coverage":"सल्लागार व्याप्ती","Live Telemetry":"थेट टेलिमेट्री","System Hardware":"सिस्टम हार्डवेअर","Diagnosis complete":"निदान पूर्ण झाले","Recommendation":"शिफारस","Recommendations":"शिफारसी","No analysis yet":"अद्याप विश्लेषण नाही","Run Analysis":"विश्लेषण चालवा","Re-analyze":"पुन्हा विश्लेषण करा","Analysis complete":"विश्लेषण पूर्ण झाले","Dismiss":"बंद करा","Pros":"फायदे","Cons":"तोटे","What it is":"हे काय आहे","Confidence:":"विश्वास:","Hide Steps":"पायऱ्या लपवा","Show BIOS Steps":"BIOS पायऱ्या दाखवा"}),
  ta: catalog({"System Profile":"கணினி சுயவிவரம்","Advisor Coverage":"Advisor கவரேஜ்","Live Telemetry":"நேரடி டெலிமெட்ரி","System Hardware":"கணினி வன்பொருள்","Diagnosis complete":"கண்டறிதல் முடிந்தது","Recommendation":"பரிந்துரை","Recommendations":"பரிந்துரைகள்","No analysis yet":"இன்னும் பகுப்பாய்வு இல்லை","Run Analysis":"பகுப்பாய்வை இயக்கவும்","Re-analyze":"மீண்டும் பகுப்பாய்வு செய்","Analysis complete":"பகுப்பாய்வு முடிந்தது","Dismiss":"மூடு","Pros":"நன்மைகள்","Cons":"குறைபாடுகள்","What it is":"இது என்ன","Confidence:":"நம்பிக்கை:","Hide Steps":"படிகளை மறை","Show BIOS Steps":"BIOS படிகளைக் காட்டு"}),
  vi: catalog({"System Profile":"Hồ sơ hệ thống","Advisor Coverage":"Phạm vi Advisor","Live Telemetry":"Đo từ xa trực tiếp","System Hardware":"Phần cứng hệ thống","Diagnosis complete":"Hoàn tất chẩn đoán","Recommendation":"Đề xuất","Recommendations":"Đề xuất","No analysis yet":"Chưa có phân tích","Run Analysis":"Chạy phân tích","Re-analyze":"Phân tích lại","Analysis complete":"Hoàn tất phân tích","Dismiss":"Đóng","Pros":"Ưu điểm","Cons":"Nhược điểm","What it is":"Nó là gì","Confidence:":"Độ tin cậy:","Hide Steps":"Ẩn các bước","Show BIOS Steps":"Hiện các bước BIOS"}),
  ur: catalog({"System Profile":"سسٹم پروفائل","Advisor Coverage":"مشیر کی کوریج","Live Telemetry":"لائیو ٹیلی میٹری","System Hardware":"سسٹم ہارڈویئر","Diagnosis complete":"تشخیص مکمل","Recommendation":"سفارش","Recommendations":"سفارشات","No analysis yet":"ابھی کوئی تجزیہ نہیں","Run Analysis":"تجزیہ چلائیں","Re-analyze":"دوبارہ تجزیہ کریں","Analysis complete":"تجزیہ مکمل","Dismiss":"بند کریں","Pros":"فوائد","Cons":"نقصانات","What it is":"یہ کیا ہے","Confidence:":"اعتماد:","Hide Steps":"مراحل چھپائیں","Show BIOS Steps":"BIOS مراحل دکھائیں"}),
} satisfies Partial<Record<Locale, Catalog>>);