import type { Locale } from "@/stores/userPreferencesStore";

/** Authenticated dashboard and live-telemetry copy. */
export const DASHBOARD_AUTH_TRANSLATIONS: Partial<Record<Locale, Record<string, string>>> = {
  en: {"Memory Pressure":"Memory Pressure","Rolling window":"Rolling window","Storage Activity":"Storage Activity","Read / Write":"Read / Write","System Rhythm":"System Rhythm","Used":"Used","Total":"Total","Free":"Free","Read":"Read","Write":"Write","Active":"Active","Unavailable":"Unavailable","Collecting telemetry…":"Collecting telemetry…","Live System Monitor":"Live System Monitor","Spike":"Spike","Collapse graph":"Collapse graph","Expand graph":"Expand graph","Click to reset view":"Click to reset view","Click to focus this metric":"Click to focus this metric","Waiting for telemetry data…":"Waiting for telemetry data…","Disk":"Disk","Net":"Net"},
  "zh-CN": {"Memory Pressure":"内存压力","Rolling window":"滚动窗口","Storage Activity":"存储活动","Read / Write":"读取 / 写入","System Rhythm":"系统节奏","Used":"已用","Total":"总计","Free":"空闲","Read":"读取","Write":"写入","Active":"活动","Unavailable":"不可用","Collecting telemetry…":"正在收集遥测数据…","Live System Monitor":"实时系统监视器","Spike":"峰值","Collapse graph":"收起图表","Expand graph":"展开图表","Click to reset view":"点击重置视图","Click to focus this metric":"点击聚焦此指标","Waiting for telemetry data…":"正在等待遥测数据…","Disk":"磁盘","Net":"网络"},
  es: {"Memory Pressure":"Presión de memoria","Rolling window":"Ventana móvil","Storage Activity":"Actividad de almacenamiento","Read / Write":"Lectura / escritura","System Rhythm":"Ritmo del sistema","Used":"Usado","Total":"Total","Free":"Libre","Read":"Lectura","Write":"Escritura","Active":"Activo","Unavailable":"No disponible","Collecting telemetry…":"Recopilando telemetría…","Live System Monitor":"Monitor del sistema en vivo","Spike":"Pico","Collapse graph":"Contraer gráfico","Expand graph":"Expandir gráfico","Click to reset view":"Haz clic para restablecer la vista","Click to focus this metric":"Haz clic para enfocar esta métrica","Waiting for telemetry data…":"Esperando datos de telemetría…","Disk":"Disco","Net":"Red"},
  hi: {"Memory Pressure":"मेमोरी दबाव","Rolling window":"रोलिंग विंडो","Storage Activity":"स्टोरेज गतिविधि","Read / Write":"रीड / राइट","System Rhythm":"सिस्टम रिदम","Used":"उपयोग किया गया","Total":"कुल","Free":"खाली","Read":"रीड","Write":"राइट","Active":"सक्रिय","Unavailable":"अनुपलब्ध","Collecting telemetry…":"टेलीमेट्री एकत्र की जा रही है…","Live System Monitor":"लाइव सिस्टम मॉनिटर","Spike":"स्पाइक","Collapse graph":"ग्राफ़ संक्षिप्त करें","Expand graph":"ग्राफ़ विस्तृत करें","Click to reset view":"व्यू रीसेट करने के लिए क्लिक करें","Click to focus this metric":"इस मेट्रिक पर फ़ोकस करने के लिए क्लिक करें","Waiting for telemetry data…":"टेलीमेट्री डेटा की प्रतीक्षा है…","Disk":"डिस्क","Net":"नेटवर्क"},
  ar: {"Memory Pressure":"ضغط الذاكرة","Rolling window":"نافذة متحركة","Storage Activity":"نشاط التخزين","Read / Write":"قراءة / كتابة","System Rhythm":"إيقاع النظام","Used":"مستخدم","Total":"الإجمالي","Free":"متاح","Read":"قراءة","Write":"كتابة","Active":"نشط","Unavailable":"غير متاح","Collecting telemetry…":"جارٍ جمع بيانات القياس عن بُعد…","Live System Monitor":"مراقب النظام المباشر","Spike":"ارتفاع","Collapse graph":"طي المخطط","Expand graph":"توسيع المخطط","Click to reset view":"انقر لإعادة ضبط العرض","Click to focus this metric":"انقر للتركيز على هذا المقياس","Waiting for telemetry data…":"بانتظار بيانات القياس عن بُعد…","Disk":"القرص","Net":"الشبكة"},
  "pt-BR": {"Memory Pressure":"Pressão de memória","Rolling window":"Janela deslizante","Storage Activity":"Atividade de armazenamento","Read / Write":"Leitura / gravação","System Rhythm":"Ritmo do sistema","Used":"Usado","Total":"Total","Free":"Livre","Read":"Leitura","Write":"Gravação","Active":"Ativo","Unavailable":"Indisponível","Collecting telemetry…":"Coletando telemetria…","Live System Monitor":"Monitor de sistema ao vivo","Spike":"Pico","Collapse graph":"Recolher gráfico","Expand graph":"Expandir gráfico","Click to reset view":"Clique para redefinir a visualização","Click to focus this metric":"Clique para focalizar esta métrica","Waiting for telemetry data…":"Aguardando dados de telemetria…","Disk":"Disco","Net":"Rede"},
  bn: {"Memory Pressure":"মেমরি চাপ","Rolling window":"রোলিং উইন্ডো","Storage Activity":"স্টোরেজ কার্যকলাপ","Read / Write":"রিড / রাইট","System Rhythm":"সিস্টেম রিদম","Used":"ব্যবহৃত","Total":"মোট","Free":"খালি","Read":"রিড","Write":"রাইট","Active":"সক্রিয়","Unavailable":"অনুপলব্ধ","Collecting telemetry…":"টেলিমেট্রি সংগ্রহ করা হচ্ছে…","Live System Monitor":"লাইভ সিস্টেম মনিটর","Spike":"স্পাইক","Collapse graph":"গ্রাফ সংকুচিত করুন","Expand graph":"গ্রাফ প্রসারিত করুন","Click to reset view":"ভিউ রিসেট করতে ক্লিক করুন","Click to focus this metric":"এই মেট্রিকে ফোকাস করতে ক্লিক করুন","Waiting for telemetry data…":"টেলিমেট্রি ডেটার জন্য অপেক্ষা করা হচ্ছে…","Disk":"ডিস্ক","Net":"নেটওয়ার্ক"},
  ru: {"Memory Pressure":"Нагрузка памяти","Rolling window":"Скользящее окно","Storage Activity":"Активность хранилища","Read / Write":"Чтение / запись","System Rhythm":"Ритм системы","Used":"Использовано","Total":"Всего","Free":"Свободно","Read":"Чтение","Write":"Запись","Active":"Активно","Unavailable":"Недоступно","Collecting telemetry…":"Сбор телеметрии…","Live System Monitor":"Мониторинг системы в реальном времени","Spike":"Всплеск","Collapse graph":"Свернуть график","Expand graph":"Развернуть график","Click to reset view":"Нажмите, чтобы сбросить вид","Click to focus this metric":"Нажмите, чтобы выделить этот показатель","Waiting for telemetry data…":"Ожидание данных телеметрии…","Disk":"Диск","Net":"Сеть"},
  ja: {"Memory Pressure":"メモリ負荷","Rolling window":"ローリングウィンドウ","Storage Activity":"ストレージアクティビティ","Read / Write":"読み取り / 書き込み","System Rhythm":"システムリズム","Used":"使用中","Total":"合計","Free":"空き","Read":"読み取り","Write":"書き込み","Active":"稼働中","Unavailable":"利用不可","Collecting telemetry…":"テレメトリを収集中…","Live System Monitor":"ライブシステムモニター","Spike":"急上昇","Collapse graph":"グラフを折りたたむ","Expand graph":"グラフを展開","Click to reset view":"クリックして表示をリセット","Click to focus this metric":"クリックしてこの指標に注目","Waiting for telemetry data…":"テレメトリデータを待機中…","Disk":"ディスク","Net":"ネットワーク"},
  pa: {"Memory Pressure":"ਮੈਮੋਰੀ ਦਬਾਅ","Rolling window":"ਰੋਲਿੰਗ ਵਿੰਡੋ","Storage Activity":"ਸਟੋਰੇਜ ਗਤੀਵਿਧੀ","Read / Write":"ਰੀਡ / ਰਾਈਟ","System Rhythm":"ਸਿਸਟਮ ਰਿਦਮ","Used":"ਵਰਤਿਆ","Total":"ਕੁੱਲ","Free":"ਖਾਲੀ","Read":"ਰੀਡ","Write":"ਰਾਈਟ","Active":"ਸਰਗਰਮ","Unavailable":"ਅਣਉਪਲਬਧ","Collecting telemetry…":"ਟੈਲੀਮੈਟਰੀ ਇਕੱਠੀ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ…","Live System Monitor":"ਲਾਈਵ ਸਿਸਟਮ ਮਾਨੀਟਰ","Spike":"ਸਪਾਈਕ","Collapse graph":"ਗ੍ਰਾਫ ਸਮੇਟੋ","Expand graph":"ਗ੍ਰਾਫ ਫੈਲਾਓ","Click to reset view":"ਵਿਊ ਰੀਸੈਟ ਕਰਨ ਲਈ ਕਲਿੱਕ ਕਰੋ","Click to focus this metric":"ਇਸ ਮੈਟ੍ਰਿਕ 'ਤੇ ਫੋਕਸ ਕਰਨ ਲਈ ਕਲਿੱਕ ਕਰੋ","Waiting for telemetry data…":"ਟੈਲੀਮੈਟਰੀ ਡੇਟਾ ਦੀ ਉਡੀਕ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ…","Disk":"ਡਿਸਕ","Net":"ਨੈੱਟਵਰਕ"},
  de: {"Memory Pressure":"Speicherauslastung","Rolling window":"Gleitendes Fenster","Storage Activity":"Speicheraktivität","Read / Write":"Lesen / Schreiben","System Rhythm":"Systemrhythmus","Used":"Verwendet","Total":"Gesamt","Free":"Frei","Read":"Lesen","Write":"Schreiben","Active":"Aktiv","Unavailable":"Nicht verfügbar","Collecting telemetry…":"Telemetrie wird erfasst…","Live System Monitor":"Live-Systemmonitor","Spike":"Spitze","Collapse graph":"Diagramm einklappen","Expand graph":"Diagramm ausklappen","Click to reset view":"Klicken, um die Ansicht zurückzusetzen","Click to focus this metric":"Klicken, um diese Metrik zu fokussieren","Waiting for telemetry data…":"Warten auf Telemetriedaten…","Disk":"Datenträger","Net":"Netzwerk"},
  id: {"Memory Pressure":"Tekanan memori","Rolling window":"Jendela bergulir","Storage Activity":"Aktivitas penyimpanan","Read / Write":"Baca / tulis","System Rhythm":"Irama sistem","Used":"Digunakan","Total":"Total","Free":"Kosong","Read":"Baca","Write":"Tulis","Active":"Aktif","Unavailable":"Tidak tersedia","Collecting telemetry…":"Mengumpulkan telemetri…","Live System Monitor":"Monitor sistem langsung","Spike":"Lonjakan","Collapse graph":"Ciutkan grafik","Expand graph":"Perluas grafik","Click to reset view":"Klik untuk mengatur ulang tampilan","Click to focus this metric":"Klik untuk fokus pada metrik ini","Waiting for telemetry data…":"Menunggu data telemetri…","Disk":"Disk","Net":"Jaringan"},
  ko: {"Memory Pressure":"메모리 압력","Rolling window":"롤링 창","Storage Activity":"저장소 활동","Read / Write":"읽기 / 쓰기","System Rhythm":"시스템 리듬","Used":"사용됨","Total":"합계","Free":"여유","Read":"읽기","Write":"쓰기","Active":"활성","Unavailable":"사용할 수 없음","Collecting telemetry…":"텔레메트리를 수집하는 중…","Live System Monitor":"실시간 시스템 모니터","Spike":"급증","Collapse graph":"그래프 접기","Expand graph":"그래프 펼치기","Click to reset view":"보기를 재설정하려면 클릭","Click to focus this metric":"이 지표에 집중하려면 클릭","Waiting for telemetry data…":"텔레메트리 데이터를 기다리는 중…","Disk":"디스크","Net":"네트워크"},
  fr: {"Memory Pressure":"Pression mémoire","Rolling window":"Fenêtre glissante","Storage Activity":"Activité de stockage","Read / Write":"Lecture / écriture","System Rhythm":"Rythme du système","Used":"Utilisé","Total":"Total","Free":"Libre","Read":"Lecture","Write":"Écriture","Active":"Actif","Unavailable":"Indisponible","Collecting telemetry…":"Collecte des données de télémétrie…","Live System Monitor":"Moniteur système en direct","Spike":"Pic","Collapse graph":"Réduire le graphique","Expand graph":"Développer le graphique","Click to reset view":"Cliquez pour réinitialiser la vue","Click to focus this metric":"Cliquez pour cibler cette mesure","Waiting for telemetry data…":"En attente des données de télémétrie…","Disk":"Disque","Net":"Réseau"},
  te: {"Memory Pressure":"మెమరీ ఒత్తిడి","Rolling window":"రోలింగ్ విండో","Storage Activity":"నిల్వ కార్యాచరణ","Read / Write":"రీడ్ / రైట్","System Rhythm":"సిస్టమ్ రిథమ్","Used":"ఉపయోగించినది","Total":"మొత్తం","Free":"ఖాళీ","Read":"రీడ్","Write":"రైట్","Active":"సక్రియం","Unavailable":"అందుబాటులో లేదు","Collecting telemetry…":"టెలిమెట్రీని సేకరిస్తోంది…","Live System Monitor":"లైవ్ సిస్టమ్ మానిటర్","Spike":"స్పైక్","Collapse graph":"గ్రాఫ్‌ను కుదించు","Expand graph":"గ్రాఫ్‌ను విస్తరించు","Click to reset view":"వీక్షణను రీసెట్ చేయడానికి క్లిక్ చేయండి","Click to focus this metric":"ఈ మెట్రిక్‌పై దృష్టి పెట్టడానికి క్లిక్ చేయండి","Waiting for telemetry data…":"టెలిమెట్రీ డేటా కోసం వేచి ఉంది…","Disk":"డిస్క్","Net":"నెట్‌వర్క్"},
  tr: {"Memory Pressure":"Bellek basıncı","Rolling window":"Kayan pencere","Storage Activity":"Depolama etkinliği","Read / Write":"Okuma / yazma","System Rhythm":"Sistem ritmi","Used":"Kullanılan","Total":"Toplam","Free":"Boş","Read":"Okuma","Write":"Yazma","Active":"Etkin","Unavailable":"Kullanılamıyor","Collecting telemetry…":"Telemetri toplanıyor…","Live System Monitor":"Canlı sistem monitörü","Spike":"Ani artış","Collapse graph":"Grafiği daralt","Expand graph":"Grafiği genişlet","Click to reset view":"Görünümü sıfırlamak için tıklayın","Click to focus this metric":"Bu ölçüme odaklanmak için tıklayın","Waiting for telemetry data…":"Telemetri verileri bekleniyor…","Disk":"Disk","Net":"Ağ"},
  mr: {"Memory Pressure":"मेमरी दाब","Rolling window":"रोलिंग विंडो","Storage Activity":"स्टोरेज क्रियाकलाप","Read / Write":"रीड / राइट","System Rhythm":"सिस्टम लय","Used":"वापरलेले","Total":"एकूण","Free":"मोकळे","Read":"रीड","Write":"राइट","Active":"सक्रिय","Unavailable":"अनुपलब्ध","Collecting telemetry…":"टेलिमेट्री गोळा करत आहे…","Live System Monitor":"लाइव्ह सिस्टम मॉनिटर","Spike":"स्पाइक","Collapse graph":"ग्राफ संकुचित करा","Expand graph":"ग्राफ विस्तृत करा","Click to reset view":"दृश्य रीसेट करण्यासाठी क्लिक करा","Click to focus this metric":"या मेट्रिकवर लक्ष केंद्रित करण्यासाठी क्लिक करा","Waiting for telemetry data…":"टेलिमेट्री डेटाची प्रतीक्षा करत आहे…","Disk":"डिस्क","Net":"नेटवर्क"},
  ta: {"Memory Pressure":"நினைவக அழுத்தம்","Rolling window":"உருளும் சாளரம்","Storage Activity":"சேமிப்பக செயல்பாடு","Read / Write":"படித்தல் / எழுதுதல்","System Rhythm":"கணினி தாளம்","Used":"பயன்படுத்தியது","Total":"மொத்தம்","Free":"காலி","Read":"படித்தல்","Write":"எழுதுதல்","Active":"செயலில்","Unavailable":"கிடைக்கவில்லை","Collecting telemetry…":"டெலிமெட்ரி சேகரிக்கப்படுகிறது…","Live System Monitor":"நேரடி கணினி கண்காணிப்பான்","Spike":"உச்சம்","Collapse graph":"வரைபடத்தைச் சுருக்கு","Expand graph":"வரைபடத்தை விரிவாக்கு","Click to reset view":"காட்சியை மீட்டமைக்க கிளிக் செய்யவும்","Click to focus this metric":"இந்த அளவீட்டில் கவனம் செலுத்த கிளிக் செய்யவும்","Waiting for telemetry data…":"டெலிமெட்ரி தரவுக்காக காத்திருக்கிறது…","Disk":"வட்டு","Net":"பிணையம்"},
  vi: {"Memory Pressure":"Áp lực bộ nhớ","Rolling window":"Cửa sổ cuộn","Storage Activity":"Hoạt động lưu trữ","Read / Write":"Đọc / ghi","System Rhythm":"Nhịp hệ thống","Used":"Đã dùng","Total":"Tổng","Free":"Trống","Read":"Đọc","Write":"Ghi","Active":"Hoạt động","Unavailable":"Không khả dụng","Collecting telemetry…":"Đang thu thập dữ liệu đo từ xa…","Live System Monitor":"Trình theo dõi hệ thống trực tiếp","Spike":"Đột biến","Collapse graph":"Thu gọn biểu đồ","Expand graph":"Mở rộng biểu đồ","Click to reset view":"Nhấp để đặt lại chế độ xem","Click to focus this metric":"Nhấp để tập trung vào chỉ số này","Waiting for telemetry data…":"Đang chờ dữ liệu đo từ xa…","Disk":"Đĩa","Net":"Mạng"},
  ur: {"Memory Pressure":"میموری دباؤ","Rolling window":"رولنگ ونڈو","Storage Activity":"اسٹوریج سرگرمی","Read / Write":"ریڈ / رائٹ","System Rhythm":"سسٹم ردھم","Used":"استعمال شدہ","Total":"کل","Free":"خالی","Read":"ریڈ","Write":"رائٹ","Active":"فعال","Unavailable":"دستیاب نہیں","Collecting telemetry…":"ٹیلی میٹری جمع کی جا رہی ہے…","Live System Monitor":"لائیو سسٹم مانیٹر","Spike":"اچانک اضافہ","Collapse graph":"گراف سمیٹیں","Expand graph":"گراف پھیلائیں","Click to reset view":"ویو ری سیٹ کرنے کے لیے کلک کریں","Click to focus this metric":"اس میٹرک پر توجہ کے لیے کلک کریں","Waiting for telemetry data…":"ٹیلی میٹری ڈیٹا کا انتظار ہے…","Disk":"ڈسک","Net":"نیٹ ورک"},
};

// Keep chart labels unambiguous in locales where a short technical label
// would otherwise be identical to its English source.
if (DASHBOARD_AUTH_TRANSLATIONS.es) DASHBOARD_AUTH_TRANSLATIONS.es.Total = "Total general";
if (DASHBOARD_AUTH_TRANSLATIONS["pt-BR"]) DASHBOARD_AUTH_TRANSLATIONS["pt-BR"].Total = "Total geral";
if (DASHBOARD_AUTH_TRANSLATIONS.fr) DASHBOARD_AUTH_TRANSLATIONS.fr.Total = "Total général";
if (DASHBOARD_AUTH_TRANSLATIONS.id) {
  DASHBOARD_AUTH_TRANSLATIONS.id.Total = "Total keseluruhan";
  DASHBOARD_AUTH_TRANSLATIONS.id.Disk = "Cakram";
}
if (DASHBOARD_AUTH_TRANSLATIONS.tr) DASHBOARD_AUTH_TRANSLATIONS.tr.Disk = "Disk sürücüsü";