import type { Locale } from "@/stores/userPreferencesStore";

/**
 * Authenticated Driver Intelligence and Latency Analyzer copy.  English source
 * text is deliberately used as the key so feature UI can call t() directly.
 */
type DriverLatencyCatalog = Record<string, string>;

const en: DriverLatencyCatalog = {
  "Health": "Health", "Installed": "Installed", "Latest known": "Latest known",
  "Latest released": "Latest released", "What's new": "What's new", "Known issues": "Known issues",
  "Close panel (Esc)": "Close panel (Esc)", "Close (Esc)": "Close (Esc)",
  "Update History": "Update History", "Loading history…": "Loading history…", "Try again": "Try again",
  "No updates logged yet": "No updates logged yet", "Restore": "Restore", "Remove this entry": "Remove this entry",
  "Unlimited": "Unlimited", "Collecting": "Collecting", "Stopped": "Stopped", "collected": "collected",
  "sample collected": "sample collected", "samples collected": "samples collected", "remaining": "remaining",
  "Installed Kernel Drivers": "Installed Kernel Drivers", "running": "running", "Description": "Description",
  "Type": "Type", "Impact": "Impact", "Suggested Action": "Suggested Action", "Show fewer": "Show fewer",
  "Show all": "Show all", "drivers": "drivers", "click for details": "click for details",
  "Your system shows very low DPC and interrupt activity. Suitable for real-time audio and low-latency gaming.": "Your system shows very low DPC and interrupt activity. Suitable for real-time audio and low-latency gaming.",
  "DPC and interrupt activity is within normal range. Should be suitable for most gaming and audio workloads.": "DPC and interrupt activity is within normal range. Should be suitable for most gaming and audio workloads.",
  "Elevated DPC or interrupt activity detected. May cause occasional audio dropouts or input timing variance.": "Elevated DPC or interrupt activity detected. May cause occasional audio dropouts or input timing variance.",
  "High DPC or interrupt overhead observed. Review the driver table for potential problem drivers.": "High DPC or interrupt overhead observed. Review the driver table for potential problem drivers.",
  "Severe DPC or interrupt activity detected. Real-time workloads are likely affected. Investigate problem drivers.": "Severe DPC or interrupt activity detected. Real-time workloads are likely affected. Investigate problem drivers.",
  "Collecting samples — run the analyzer for at least 15–30 seconds for a meaningful result.": "Collecting samples — run the analyzer for at least 15–30 seconds for a meaningful result.",
  "% CPU in DPCs": "% CPU in DPCs", "% CPU in ISRs": "% CPU in ISRs", "highest single sample": "highest single sample",
  "avg per second": "avg per second", "/sec highest": "/sec highest", "user-mode restriction": "user-mode restriction",
  "2s interval": "2s interval", "elapsed time": "elapsed time", "DPC%": "DPC%", "ISR%": "ISR%", "PF×100/s": "PF×100/s",
  "Scheduler Responsiveness": "Scheduler Responsiveness", "Network-Driver Latency Risk": "Network-Driver Latency Risk",
  "GPU-Driver Latency Risk": "GPU-Driver Latency Risk", "Storage-Driver Latency Risk": "Storage-Driver Latency Risk",
  "Background Interruption Risk": "Background Interruption Risk", "Avg DPC%": "Avg DPC%", "Peak DPC%": "Peak DPC%",
  "Avg ISR%": "Avg ISR%", "Peak ISR%": "Peak ISR%", "overall": "overall",
  "Checking hardware…": "Checking hardware…", "Reading firmware…": "Reading firmware…",
  "Reading installed drivers…": "Reading installed drivers…", "Comparing cloud database…": "Comparing cloud database…",
  "Running analysis…": "Running analysis…", "Building recommendations…": "Building recommendations…",
  "Up to date": "Up to date", "Newer than database": "Newer than database", "Update available": "Update available",
  "Action needed": "Action needed", "Not detected": "Not detected",
  "Responsive": "Responsive", "Moderate": "Moderate", "Sluggish": "Sluggish",
  "Limited in user mode": "Limited in user mode", "Gaming Responsiveness": "Gaming Responsiveness",
  "Overall Score": "Overall Score",
  "This assessment evaluates Windows scheduling and driver behaviour only. It does not measure network ping, monitor latency, mouse/keyboard latency, in-game FPS, or end-to-end input latency.": "This assessment evaluates Windows scheduling and driver behaviour only. It does not measure network ping, monitor latency, mouse/keyboard latency, in-game FPS, or end-to-end input latency.",
};

const copy = (values: DriverLatencyCatalog): DriverLatencyCatalog => ({ ...en, ...values });

export const DRIVER_LATENCY_AUTH_TRANSLATIONS: Partial<Record<Locale, DriverLatencyCatalog>> = {
  en,
  "zh-CN": copy({ Health: "健康", Installed: "已安装", "Latest known": "已知最新版本", "Latest released": "最新发布", "What's new": "更新内容", "Known issues": "已知问题", "Update History": "更新历史", "Loading history…": "正在加载历史记录…", "Try again": "重试", "No updates logged yet": "尚未记录更新", Restore: "还原", "Remove this entry": "删除此条目", Unlimited: "不限时", Collecting: "正在收集", Stopped: "已停止", collected: "已收集", "sample collected": "个样本已收集", "samples collected": "个样本已收集", remaining: "剩余", "Installed Kernel Drivers": "已安装的内核驱动程序", running: "正在运行", Description: "描述", Type: "类型", Impact: "影响", "Suggested Action": "建议操作", "Show fewer": "显示更少", "Show all": "显示全部", drivers: "个驱动程序", "click for details": "点击查看详情" }),
  es: copy({ Health: "Estado", Installed: "Instalado", "Latest known": "Última conocida", "Latest released": "Última publicación", "What's new": "Novedades", "Known issues": "Problemas conocidos", "Update History": "Historial de actualizaciones", "Loading history…": "Cargando historial…", "Try again": "Intentar de nuevo", "No updates logged yet": "Aún no hay actualizaciones registradas", Restore: "Restaurar", "Remove this entry": "Eliminar esta entrada", Unlimited: "Ilimitado", Collecting: "Recopilando", Stopped: "Detenido", collected: "recopilado", "sample collected": "muestra recopilada", "samples collected": "muestras recopiladas", remaining: "restantes", "Installed Kernel Drivers": "Controladores de núcleo instalados", running: "en ejecución", Description: "Descripción", Type: "Tipo", Impact: "Impacto", "Suggested Action": "Acción sugerida", "Show fewer": "Mostrar menos", "Show all": "Mostrar todos", drivers: "controladores", "click for details": "haz clic para ver detalles" }),
  de: copy({ Health: "Zustand", Installed: "Installiert", "Latest known": "Neueste bekannte", "Latest released": "Neueste Veröffentlichung", "What's new": "Neuigkeiten", "Known issues": "Bekannte Probleme", "Update History": "Updateverlauf", "Loading history…": "Verlauf wird geladen…", "Try again": "Erneut versuchen", "No updates logged yet": "Noch keine Updates protokolliert", Restore: "Wiederherstellen", "Remove this entry": "Diesen Eintrag entfernen", Unlimited: "Unbegrenzt", Collecting: "Erfassung läuft", Stopped: "Gestoppt", collected: "erfasst", "sample collected": "Messwert erfasst", "samples collected": "Messwerte erfasst", remaining: "verbleibend", "Installed Kernel Drivers": "Installierte Kerneltreiber", running: "aktiv", Description: "Beschreibung", Type: "Typ", Impact: "Auswirkung", "Suggested Action": "Empfohlene Aktion", "Show fewer": "Weniger anzeigen", "Show all": "Alle anzeigen", drivers: "Treiber", "click for details": "für Details klicken" }),
  fr: copy({ Health: "État", Installed: "Installé", "Latest known": "Dernière version connue", "Latest released": "Dernière publication", "What's new": "Nouveautés", "Known issues": "Problèmes connus", "Update History": "Historique des mises à jour", "Loading history…": "Chargement de l’historique…", "Try again": "Réessayer", "No updates logged yet": "Aucune mise à jour enregistrée", Restore: "Restaurer", "Remove this entry": "Supprimer cette entrée", Unlimited: "Illimité", Collecting: "Collecte en cours", Stopped: "Arrêté", collected: "collecté", "sample collected": "échantillon collecté", "samples collected": "échantillons collectés", remaining: "restantes", "Installed Kernel Drivers": "Pilotes du noyau installés", running: "en cours", Description: "Description", Type: "Type", Impact: "Impact", "Suggested Action": "Action suggérée", "Show fewer": "Afficher moins", "Show all": "Afficher tous", drivers: "pilotes", "click for details": "cliquer pour les détails" }),
  "pt-BR": copy({ Health: "Integridade", Installed: "Instalado", "Latest known": "Mais recente conhecida", "Latest released": "Última versão lançada", "What's new": "Novidades", "Known issues": "Problemas conhecidos", "Update History": "Histórico de atualizações", "Loading history…": "Carregando histórico…", "Try again": "Tentar novamente", "No updates logged yet": "Nenhuma atualização registrada", Restore: "Restaurar", "Remove this entry": "Remover esta entrada", Unlimited: "Ilimitado", Collecting: "Coletando", Stopped: "Parado", collected: "coletado", "sample collected": "amostra coletada", "samples collected": "amostras coletadas", remaining: "restantes", "Installed Kernel Drivers": "Drivers de kernel instalados", running: "em execução", Description: "Descrição", Type: "Tipo", Impact: "Impacto", "Suggested Action": "Ação sugerida", "Show fewer": "Mostrar menos", "Show all": "Mostrar todos", drivers: "drivers", "click for details": "clique para detalhes" }),
  ru: copy({ Health: "Состояние", Installed: "Установлено", "Latest known": "Последняя известная", "Latest released": "Последний выпуск", "What's new": "Что нового", "Known issues": "Известные проблемы", "Update History": "История обновлений", "Loading history…": "Загрузка истории…", "Try again": "Повторить", "No updates logged yet": "Обновлений ещё нет", Restore: "Восстановить", "Remove this entry": "Удалить эту запись", Unlimited: "Без ограничений", Collecting: "Сбор данных", Stopped: "Остановлено", collected: "собрано", "sample collected": "образец собран", "samples collected": "образцов собрано", remaining: "осталось", "Installed Kernel Drivers": "Установленные драйверы ядра", running: "работают", Description: "Описание", Type: "Тип", Impact: "Влияние", "Suggested Action": "Рекомендуемое действие", "Show fewer": "Показать меньше", "Show all": "Показать все", drivers: "драйверов", "click for details": "нажмите для подробностей" }),
  ja: copy({ Health: "状態", Installed: "インストール済み", "Latest known": "既知の最新", "Latest released": "最新リリース", "What's new": "新機能", "Known issues": "既知の問題", "Update History": "更新履歴", "Loading history…": "履歴を読み込み中…", "Try again": "再試行", "No updates logged yet": "更新はまだ記録されていません", Restore: "復元", "Remove this entry": "この項目を削除", Unlimited: "無制限", Collecting: "収集中", Stopped: "停止", collected: "収集済み", "sample collected": "サンプルを収集", "samples collected": "サンプルを収集", remaining: "残り", "Installed Kernel Drivers": "インストール済みカーネルドライバー", running: "実行中", Description: "説明", Type: "種類", Impact: "影響", "Suggested Action": "推奨操作", "Show fewer": "表示を減らす", "Show all": "すべて表示", drivers: "ドライバー", "click for details": "クリックして詳細を表示" }),
  ko: copy({ Health: "상태", Installed: "설치됨", "Latest known": "알려진 최신 버전", "Latest released": "최신 릴리스", "What's new": "새로운 기능", "Known issues": "알려진 문제", "Update History": "업데이트 기록", "Loading history…": "기록을 불러오는 중…", "Try again": "다시 시도", "No updates logged yet": "기록된 업데이트가 없습니다", Restore: "복원", "Remove this entry": "이 항목 제거", Unlimited: "무제한", Collecting: "수집 중", Stopped: "중지됨", collected: "수집됨", "sample collected": "샘플 수집됨", "samples collected": "샘플 수집됨", remaining: "남음", "Installed Kernel Drivers": "설치된 커널 드라이버", running: "실행 중", Description: "설명", Type: "유형", Impact: "영향", "Suggested Action": "권장 작업", "Show fewer": "간단히 보기", "Show all": "모두 보기", drivers: "드라이버", "click for details": "클릭하여 세부 정보 보기" }),
  hi: copy({ Health: "स्थिति", Installed: "स्थापित", "Latest known": "नवीनतम ज्ञात", "Latest released": "नवीनतम रिलीज़", "What's new": "नया क्या है", "Known issues": "ज्ञात समस्याएँ", "Update History": "अपडेट इतिहास", "Loading history…": "इतिहास लोड हो रहा है…", "Try again": "फिर प्रयास करें", "No updates logged yet": "अभी कोई अपडेट लॉग नहीं है", Restore: "पुनर्स्थापित करें", Unlimited: "असीमित", Collecting: "संग्रह हो रहा है", Stopped: "रुका", Description: "विवरण", Type: "प्रकार", Impact: "प्रभाव", "Suggested Action": "सुझाई गई कार्रवाई" }),
  ar: copy({ Health: "الحالة", Installed: "مثبت", "Latest known": "أحدث إصدار معروف", "Latest released": "أحدث إصدار", "What's new": "ما الجديد", "Known issues": "المشكلات المعروفة", "Update History": "سجل التحديثات", "Loading history…": "جارٍ تحميل السجل…", "Try again": "حاول مجددًا", "No updates logged yet": "لا توجد تحديثات مسجلة بعد", Restore: "استعادة", Unlimited: "غير محدود", Collecting: "جارٍ الجمع", Stopped: "متوقف", Description: "الوصف", Type: "النوع", Impact: "التأثير", "Suggested Action": "الإجراء المقترح" }),
  bn: copy({ Health: "অবস্থা", Installed: "ইনস্টল করা", "Latest known": "সর্বশেষ জানা", "Latest released": "সর্বশেষ প্রকাশিত", "What's new": "নতুন কী", "Known issues": "পরিচিত সমস্যা", "Update History": "আপডেট ইতিহাস", "Loading history…": "ইতিহাস লোড হচ্ছে…", "Try again": "আবার চেষ্টা করুন", Restore: "পুনরুদ্ধার", Unlimited: "সীমাহীন", Collecting: "সংগ্রহ করা হচ্ছে", Stopped: "বন্ধ", Description: "বিবরণ", Type: "ধরন", Impact: "প্রভাব", "Suggested Action": "প্রস্তাবিত পদক্ষেপ" }),
  pa: copy({ Health: "ਸਥਿਤੀ", Installed: "ਇੰਸਟਾਲ ਕੀਤਾ", "Latest known": "ਨਵਾਂਤਮ ਜਾਣਿਆ", "Latest released": "ਨਵਾਂਤਮ ਰਿਲੀਜ਼", "What's new": "ਨਵਾਂ ਕੀ ਹੈ", "Known issues": "ਜਾਣੀਆਂ ਸਮੱਸਿਆਵਾਂ", "Update History": "ਅੱਪਡੇਟ ਇਤਿਹਾਸ", "Loading history…": "ਇਤਿਹਾਸ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…", "Try again": "ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ", Restore: "ਬਹਾਲ ਕਰੋ", Unlimited: "ਅਸੀਮਤ", Collecting: "ਇਕੱਠਾ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ", Stopped: "ਰੁਕਿਆ", Description: "ਵੇਰਵਾ", Type: "ਕਿਸਮ", Impact: "ਪ੍ਰਭਾਵ", "Suggested Action": "ਸੁਝਾਈ ਕਾਰਵਾਈ" }),
  id: copy({ Health: "Kondisi", Installed: "Terpasang", "Latest known": "Terbaru yang diketahui", "Latest released": "Rilis terbaru", "What's new": "Yang baru", "Known issues": "Masalah yang diketahui", "Update History": "Riwayat pembaruan", "Loading history…": "Memuat riwayat…", "Try again": "Coba lagi", Restore: "Pulihkan", Unlimited: "Tanpa batas", Collecting: "Mengumpulkan", Stopped: "Dihentikan", Description: "Deskripsi", Type: "Jenis", Impact: "Dampak", "Suggested Action": "Tindakan yang disarankan" }),
  te: copy({ Health: "స్థితి", Installed: "ఇన్‌స్టాల్ చేయబడింది", "Latest known": "తెలిసిన తాజాది", "Latest released": "తాజా విడుదల", "What's new": "కొత్తవి", "Known issues": "తెలిసిన సమస్యలు", "Update History": "నవీకరణ చరిత్ర", "Loading history…": "చరిత్ర లోడ్ అవుతోంది…", "Try again": "మళ్లీ ప్రయత్నించండి", Restore: "పునరుద్ధరించు", Unlimited: "అపరిమితం", Collecting: "సేకరిస్తోంది", Stopped: "ఆపబడింది", Description: "వివరణ", Type: "రకం", Impact: "ప్రభావం", "Suggested Action": "సూచించిన చర్య" }),
  tr: copy({ Health: "Durum", Installed: "Yüklü", "Latest known": "Bilinen en güncel", "Latest released": "Son sürüm", "What's new": "Yenilikler", "Known issues": "Bilinen sorunlar", "Update History": "Güncelleme geçmişi", "Loading history…": "Geçmiş yükleniyor…", "Try again": "Tekrar dene", Restore: "Geri yükle", Unlimited: "Sınırsız", Collecting: "Toplanıyor", Stopped: "Durduruldu", Description: "Açıklama", Type: "Tür", Impact: "Etki", "Suggested Action": "Önerilen işlem" }),
  mr: copy({ Health: "स्थिती", Installed: "स्थापित", "Latest known": "नवीनतम ज्ञात", "Latest released": "नवीनतम प्रकाशन", "What's new": "नवीन काय", "Known issues": "ज्ञात समस्या", "Update History": "अद्यतन इतिहास", "Loading history…": "इतिहास लोड होत आहे…", "Try again": "पुन्हा प्रयत्न करा", Restore: "पुनर्संचयित करा", Unlimited: "अमर्यादित", Collecting: "संकलन सुरू आहे", Stopped: "थांबवले", Description: "वर्णन", Type: "प्रकार", Impact: "प्रभाव", "Suggested Action": "सुचवलेली कृती" }),
  ta: copy({ Health: "நிலை", Installed: "நிறுவப்பட்டது", "Latest known": "அறியப்பட்ட சமீபத்தியது", "Latest released": "சமீபத்திய வெளியீடு", "What's new": "புதியவை", "Known issues": "அறியப்பட்ட சிக்கல்கள்", "Update History": "புதுப்பிப்பு வரலாறு", "Loading history…": "வரலாறு ஏற்றப்படுகிறது…", "Try again": "மீண்டும் முயற்சிக்கவும்", Restore: "மீட்டமை", Unlimited: "வரம்பற்றது", Collecting: "சேகரிக்கப்படுகிறது", Stopped: "நிறுத்தப்பட்டது", Description: "விளக்கம்", Type: "வகை", Impact: "பாதிப்பு", "Suggested Action": "பரிந்துரைக்கப்பட்ட செயல்" }),
  vi: copy({ Health: "Trạng thái", Installed: "Đã cài đặt", "Latest known": "Mới nhất đã biết", "Latest released": "Bản phát hành mới nhất", "What's new": "Có gì mới", "Known issues": "Sự cố đã biết", "Update History": "Lịch sử cập nhật", "Loading history…": "Đang tải lịch sử…", "Try again": "Thử lại", Restore: "Khôi phục", Unlimited: "Không giới hạn", Collecting: "Đang thu thập", Stopped: "Đã dừng", Description: "Mô tả", Type: "Loại", Impact: "Tác động", "Suggested Action": "Hành động đề xuất" }),
  ur: copy({ Health: "حالت", Installed: "انسٹال شدہ", "Latest known": "تازہ ترین معلوم", "Latest released": "تازہ ترین اجرا", "What's new": "نیا کیا ہے", "Known issues": "معلوم مسائل", "Update History": "اپ ڈیٹ تاریخ", "Loading history…": "تاریخ لوڈ ہو رہی ہے…", "Try again": "دوبارہ کوشش کریں", Restore: "بحال کریں", Unlimited: "لامحدود", Collecting: "جمع کیا جا رہا ہے", Stopped: "روکا گیا", Description: "تفصیل", Type: "قسم", Impact: "اثر", "Suggested Action": "تجویز کردہ عمل" }),
};