import type { Locale } from "@/stores/userPreferencesStore";

/**
 * Authenticated Settings and History vocabulary.  This catalog deliberately
 * lives beside feature copy so product names, IDs, units, and API terms remain
 * untouched while the surrounding UI can be translated.
 */
export const SETTINGS_HISTORY_AUTH_TRANSLATIONS: Partial<Record<Locale, Record<string, string>>> = {
  "zh-CN": { "Actions Over Time": "操作随时间变化", "Success vs Failure": "成功与失败", "Module Usage": "模块使用情况", "No data for this range": "此范围内没有数据", "No data yet": "暂无数据", Actions: "操作", Other: "其他", "Recent Major Events": "最近的重要事件", "No actions recorded yet": "尚未记录操作", "No events match your filters": "没有事件符合筛选条件", "Clear filters": "清除筛选条件", "High impact": "高影响" },
  es: { "Actions Over Time": "Acciones a lo largo del tiempo", "Success vs Failure": "Éxitos frente a fallos", "Module Usage": "Uso de módulos", "No data for this range": "No hay datos para este intervalo", "No data yet": "Aún no hay datos", Actions: "Acciones", Other: "Otros", "Recent Major Events": "Eventos importantes recientes", "No actions recorded yet": "Aún no hay acciones registradas", "No events match your filters": "Ningún evento coincide con tus filtros", "Clear filters": "Borrar filtros", "High impact": "Alto impacto" },
  hi: { "Actions Over Time": "समय के साथ कार्रवाइयाँ", "Success vs Failure": "सफलता बनाम विफलता", "Module Usage": "मॉड्यूल उपयोग", "No data for this range": "इस सीमा के लिए कोई डेटा नहीं", "No data yet": "अभी कोई डेटा नहीं", Actions: "कार्रवाइयाँ", Other: "अन्य", "Recent Major Events": "हाल की प्रमुख घटनाएँ", "No actions recorded yet": "अभी कोई कार्रवाई दर्ज नहीं हुई", "No events match your filters": "कोई घटना आपके फ़िल्टर से मेल नहीं खाती", "Clear filters": "फ़िल्टर साफ़ करें", "High impact": "उच्च प्रभाव" },
  ar: { "Actions Over Time": "الإجراءات عبر الوقت", "Success vs Failure": "النجاح مقابل الفشل", "Module Usage": "استخدام الوحدات", "No data for this range": "لا توجد بيانات لهذا النطاق", "No data yet": "لا توجد بيانات بعد", Actions: "الإجراءات", Other: "أخرى", "Recent Major Events": "الأحداث الرئيسية الأخيرة", "No actions recorded yet": "لم تُسجل إجراءات بعد", "No events match your filters": "لا توجد أحداث تطابق عوامل التصفية", "Clear filters": "مسح عوامل التصفية", "High impact": "تأثير مرتفع" },
  "pt-BR": { "Actions Over Time": "Ações ao longo do tempo", "Success vs Failure": "Sucesso versus falha", "Module Usage": "Uso de módulos", "No data for this range": "Não há dados para este período", "No data yet": "Ainda não há dados", Actions: "Ações", Other: "Outros", "Recent Major Events": "Eventos importantes recentes", "No actions recorded yet": "Nenhuma ação registrada ainda", "No events match your filters": "Nenhum evento corresponde aos filtros", "Clear filters": "Limpar filtros", "High impact": "Alto impacto" },
  bn: { "Actions Over Time": "সময়ের সাথে কার্যক্রম", "Success vs Failure": "সফলতা বনাম ব্যর্থতা", "Module Usage": "মডিউল ব্যবহার", "No data for this range": "এই পরিসরে কোনো ডেটা নেই", "No data yet": "এখনও কোনো ডেটা নেই", Actions: "কার্যক্রম", Other: "অন্যান্য", "Recent Major Events": "সাম্প্রতিক গুরুত্বপূর্ণ ঘটনা", "No actions recorded yet": "এখনও কোনো কার্যক্রম রেকর্ড করা হয়নি", "No events match your filters": "কোনো ইভেন্ট আপনার ফিল্টারের সাথে মেলেনি", "Clear filters": "ফিল্টার মুছুন", "High impact": "উচ্চ প্রভাব" },
  ru: { "Actions Over Time": "Действия с течением времени", "Success vs Failure": "Успехи и ошибки", "Module Usage": "Использование модулей", "No data for this range": "Нет данных за этот период", "No data yet": "Данных пока нет", Actions: "Действия", Other: "Другое", "Recent Major Events": "Недавние важные события", "No actions recorded yet": "Действий пока не записано", "No events match your filters": "Нет событий, соответствующих фильтрам", "Clear filters": "Очистить фильтры", "High impact": "Высокое влияние" },
  ja: { "Actions Over Time": "時間別アクション", "Success vs Failure": "成功と失敗", "Module Usage": "モジュール使用状況", "No data for this range": "この期間のデータはありません", "No data yet": "データはまだありません", Actions: "アクション", Other: "その他", "Recent Major Events": "最近の主要イベント", "No actions recorded yet": "記録されたアクションはまだありません", "No events match your filters": "フィルターに一致するイベントはありません", "Clear filters": "フィルターをクリア", "High impact": "影響大" },
  pa: { "Actions Over Time": "ਸਮੇਂ ਅਨੁਸਾਰ ਕਾਰਵਾਈਆਂ", "Success vs Failure": "ਸਫਲਤਾ ਬਨਾਮ ਅਸਫਲਤਾ", "Module Usage": "ਮੋਡੀਊਲ ਵਰਤੋਂ", "No data for this range": "ਇਸ ਰੇਂਜ ਲਈ ਕੋਈ ਡਾਟਾ ਨਹੀਂ", "No data yet": "ਅਜੇ ਕੋਈ ਡਾਟਾ ਨਹੀਂ", Actions: "ਕਾਰਵਾਈਆਂ", Other: "ਹੋਰ", "Recent Major Events": "ਹਾਲੀਆ ਮੁੱਖ ਘਟਨਾਵਾਂ", "No actions recorded yet": "ਅਜੇ ਕੋਈ ਕਾਰਵਾਈ ਰਿਕਾਰਡ ਨਹੀਂ ਹੋਈ", "No events match your filters": "ਕੋਈ ਘਟਨਾ ਤੁਹਾਡੇ ਫਿਲਟਰਾਂ ਨਾਲ ਮੇਲ ਨਹੀਂ ਖਾਂਦੀ", "Clear filters": "ਫਿਲਟਰ ਸਾਫ਼ ਕਰੋ", "High impact": "ਉੱਚ ਪ੍ਰਭਾਵ" },
  de: { "Actions Over Time": "Aktionen im Zeitverlauf", "Success vs Failure": "Erfolg gegenüber Fehler", "Module Usage": "Modulnutzung", "No data for this range": "Keine Daten für diesen Zeitraum", "No data yet": "Noch keine Daten", Actions: "Aktionen", Other: "Andere", "Recent Major Events": "Neueste wichtige Ereignisse", "No actions recorded yet": "Noch keine Aktionen aufgezeichnet", "No events match your filters": "Keine Ereignisse entsprechen Ihren Filtern", "Clear filters": "Filter löschen", "High impact": "Hohe Auswirkung" },
  id: { "Actions Over Time": "Tindakan dari waktu ke waktu", "Success vs Failure": "Berhasil versus gagal", "Module Usage": "Penggunaan modul", "No data for this range": "Tidak ada data untuk rentang ini", "No data yet": "Belum ada data", Actions: "Tindakan", Other: "Lainnya", "Recent Major Events": "Peristiwa utama terbaru", "No actions recorded yet": "Belum ada tindakan yang direkam", "No events match your filters": "Tidak ada peristiwa yang cocok dengan filter", "Clear filters": "Hapus filter", "High impact": "Dampak tinggi" },
  ko: { "Actions Over Time": "시간별 작업", "Success vs Failure": "성공 및 실패", "Module Usage": "모듈 사용량", "No data for this range": "이 범위에 데이터가 없습니다", "No data yet": "아직 데이터가 없습니다", Actions: "작업", Other: "기타", "Recent Major Events": "최근 주요 이벤트", "No actions recorded yet": "기록된 작업이 아직 없습니다", "No events match your filters": "필터와 일치하는 이벤트가 없습니다", "Clear filters": "필터 지우기", "High impact": "높은 영향" },
  fr: { "Actions Over Time": "Actions au fil du temps", "Success vs Failure": "Réussites et échecs", "Module Usage": "Utilisation des modules", "No data for this range": "Aucune donnée pour cette période", "No data yet": "Aucune donnée pour le moment", Actions: "Actions", Other: "Autres", "Recent Major Events": "Événements majeurs récents", "No actions recorded yet": "Aucune action enregistrée", "No events match your filters": "Aucun événement ne correspond à vos filtres", "Clear filters": "Effacer les filtres", "High impact": "Impact élevé" },
  te: { "Actions Over Time": "కాలక్రమంలో చర్యలు", "Success vs Failure": "విజయం వర్సెస్ వైఫల్యం", "Module Usage": "మాడ్యూల్ వినియోగం", "No data for this range": "ఈ పరిధికి డేటా లేదు", "No data yet": "ఇంకా డేటా లేదు", Actions: "చర్యలు", Other: "ఇతర", "Recent Major Events": "ఇటీవలి ముఖ్య సంఘటనలు", "No actions recorded yet": "ఇంకా చర్యలు నమోదు కాలేదు", "No events match your filters": "మీ ఫిల్టర్‌లకు సరిపోయే సంఘటనలు లేవు", "Clear filters": "ఫిల్టర్‌లను తొలగించు", "High impact": "అధిక ప్రభావం" },
  tr: { "Actions Over Time": "Zaman içindeki eylemler", "Success vs Failure": "Başarı ve başarısızlık", "Module Usage": "Modül kullanımı", "No data for this range": "Bu aralık için veri yok", "No data yet": "Henüz veri yok", Actions: "Eylemler", Other: "Diğer", "Recent Major Events": "Son önemli olaylar", "No actions recorded yet": "Henüz eylem kaydedilmedi", "No events match your filters": "Filtrelerinizle eşleşen olay yok", "Clear filters": "Filtreleri temizle", "High impact": "Yüksek etki" },
  mr: { "Actions Over Time": "वेळेनुसार क्रिया", "Success vs Failure": "यश विरुद्ध अपयश", "Module Usage": "मॉड्यूल वापर", "No data for this range": "या श्रेणीसाठी डेटा नाही", "No data yet": "अद्याप डेटा नाही", Actions: "क्रिया", Other: "इतर", "Recent Major Events": "अलीकडील प्रमुख घटना", "No actions recorded yet": "अद्याप कोणतीही क्रिया नोंदलेली नाही", "No events match your filters": "तुमच्या फिल्टरशी कोणतीही घटना जुळत नाही", "Clear filters": "फिल्टर साफ करा", "High impact": "उच्च परिणाम" },
  ta: { "Actions Over Time": "காலப்போக்கில் செயல்கள்", "Success vs Failure": "வெற்றி எதிர் தோல்வி", "Module Usage": "தொகுதி பயன்பாடு", "No data for this range": "இந்த வரம்பிற்கு தரவு இல்லை", "No data yet": "இன்னும் தரவு இல்லை", Actions: "செயல்கள்", Other: "மற்றவை", "Recent Major Events": "சமீபத்திய முக்கிய நிகழ்வுகள்", "No actions recorded yet": "இன்னும் செயல்கள் பதிவு செய்யப்படவில்லை", "No events match your filters": "உங்கள் வடிப்பான்களுடன் நிகழ்வுகள் பொருந்தவில்லை", "Clear filters": "வடிப்பான்களை அழி", "High impact": "உயர் தாக்கம்" },
  vi: { "Actions Over Time": "Hành động theo thời gian", "Success vs Failure": "Thành công và thất bại", "Module Usage": "Mức sử dụng mô-đun", "No data for this range": "Không có dữ liệu cho phạm vi này", "No data yet": "Chưa có dữ liệu", Actions: "Hành động", Other: "Khác", "Recent Major Events": "Sự kiện quan trọng gần đây", "No actions recorded yet": "Chưa có hành động nào được ghi lại", "No events match your filters": "Không có sự kiện nào khớp bộ lọc", "Clear filters": "Xóa bộ lọc", "High impact": "Tác động cao" },
  ur: { "Actions Over Time": "وقت کے ساتھ کارروائیاں", "Success vs Failure": "کامیابی بمقابلہ ناکامی", "Module Usage": "ماڈیول کا استعمال", "No data for this range": "اس حد کے لیے کوئی ڈیٹا نہیں", "No data yet": "ابھی کوئی ڈیٹا نہیں", Actions: "کارروائیاں", Other: "دیگر", "Recent Major Events": "حالیہ اہم واقعات", "No actions recorded yet": "ابھی کوئی کارروائی ریکارڈ نہیں ہوئی", "No events match your filters": "کوئی واقعہ آپ کے فلٹرز سے مطابقت نہیں رکھتا", "Clear filters": "فلٹر صاف کریں", "High impact": "زیادہ اثر" },
};